### ISSUE TITLE
libGL + OpenCV error

### ISSUE THREAD

**Issue by sameeranees** [RoblabWh/PatchMatch#3]
Hi,
I used the following command to run the algo: `./run_video_slam -v ../orb_vocab/orb_vocab.dbow2 -c ../example/patchmatch/config.yaml -m ../example/patchmatch/video.mp4`
Running the algo on docker gives me this error: 
![Screenshot from 2023-10-28 17-16-04](https://github.com/RoblabWh/PatchMatch/assets/31915038/450ff508-149f-41c8-b3c4-aef70adc8a14)

**Comment by ndigakis** [comment]
I'm unable to reproduce this error. What are the specs of the PC you're using?

**Comment by sameeranees** [comment]
@ndigakis 
Operating System: Ubuntu 22.04 (jammy Jellyfish)
CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
Architecture: x86_64
GPU: NVIDIA GM108M [GeForce MX130]

**Comment by sameeranees** [comment]
Okay my bad, I forgot to provide a mask. It works now.

**Comment by roblab2011** [comment]
Great!!! How are the results ? To achieve real time reduce the video to HD (1920x960) and / or increase the skip-frames. In simple environments 30 should still work.

**Comment by roblab2011** [comment]
p.s. For a mask you can simply take a picture from the video and edit it with gimp for example. All black pixels are not used.

**Comment by sameeranees** [comment]
@roblab2011, 
Thanks for the information about the mask, was a bit confused how the mask was going to work before, but yeah making one with gimp helps.
With regards to the algorithm, The output displayed in the Pangolin viewer shows a roadmap with green boxes, but it doesn't seem to show the keypoints or features in the viewer.
And for some reason the mapping in the viewer appears to be somewhat delayed compared to the stream, and when the stream ends, the mapping stops as well.

**Comment by roblab2011** [comment]
PatchMatch is a multi view stereo algo. and needs 3 to 5 key frames to calculated the point cloud. More infos can be found in the paper https://arxiv.org/abs/2211.16266
