### ISSUE TITLE
opencv exception

### ISSUE THREAD

**Issue by jiekexiongda** [RoblabWh/PatchMatch#4]
Thank you for your work. I encountered this error while running a command inside a Docker container. How should I resolve it?
![image](https://github.com/RoblabWh/PatchMatch/assets/133642707/63e74ec6-5832-48ff-be88-829f78c00bda)

**Comment by ndigakis** [comment]
Are you currently using a mask? If not, try executing the same command with the inclusion of a mask. A plain white image with the same resolution as your input images should be enough.

**Comment by ndigakis** [comment]
@jiekexiongda Please try to reproduce with our newer implementation: [stella_vslam_dense](https://github.com/RoblabWh/stella_vslam_dense)
